# Generated by Django 5.1.5 on 2025-05-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20250419_2035'),
    ]

    operations = [
    ]
