# Generated by Django 5.1.5 on 2025-05-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20250520_1215'),
    ]

    operations = [
    ]
