# Generated by Django 5.1.5 on 2025-05-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20250521_1935'),
    ]

    operations = [
    ]
