# Generated by Django 5.1.5 on 2025-05-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20250521_1937'),
    ]

    operations = [
    ]
