# Generated by Django 5.1.5 on 2025-05-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20250521_2042'),
    ]

    operations = [
    ]
