# Generated by Django 5.1.5 on 2025-05-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20250521_2056'),
    ]

    operations = [
    ]
